import { Inter } from "next/font/google";
import { ThemeProvider } from "@/components/Code-Editor/theme-provider";
import { Toaster } from "react-hot-toast";

// Initialize the Inter font with Latin subsets
const inter = Inter({ subsets: ["latin"] });

// Metadata for the application
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Layout component specific to Code-Editor
export default function RootLayout({ children }) {
  return (
    <div className={inter.className}>
      <Toaster position="top-center" reverseOrder={false} />
      <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
      >
        {children}
      </ThemeProvider>
    </div>
  );
}
