import { Inter } from "next/font/google";
import "./globals.scss";

import { UserProvider } from "@auth0/nextjs-auth0/client";
import ClientWrapper from "@/components/Core/ClientWrapper";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Skill Sarthi",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider>
          <ClientWrapper>{children}</ClientWrapper>
        </UserProvider>
      </body>
    </html>
  );
}
