import { Inter } from "next/font/google";
import "./globals.scss";

import SessionWrapper from "@/components/SessionWrapper"; // your custom wrapper for next-auth
import ClientWrapper from "@/components/Core/ClientWrapper"; // optional, if you're still using it

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Skill Sarthi",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionWrapper>
          <ClientWrapper>{children}</ClientWrapper>
        </SessionWrapper>
      </body>
    </html>
  );
}
